packages:
  - "."
  - "../../packages/media-domain"
allowBuilds:
  '@ffprobe-installer/darwin-arm64': true
  '@ffprobe-installer/darwin-x64': true
  '@ffprobe-installer/linux-arm64': true
  '@ffprobe-installer/linux-x64': true
  '@ffprobe-installer/win32-ia32': true
  '@ffprobe-installer/win32-x64': true
  electron: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  fs-xattr: true
  macos-alias: true
  sharp: true
blockExoticSubdeps: true
minimumReleaseAge: 10080
nodeLinker: hoisted
overrides:
  '@electron/node-gyp': 10.2.0-electron.2
  yauzl: "3.3.1"
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
