allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  sharp: true
patchedDependencies:
  '@electron-forge/plugin-vite@7.11.1': patches/@electron-forge__plugin-vite@7.11.1.patch
