/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/_gallery'
import { Route as GalleryIndexRouteImport } from './routes/_gallery/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as InternalOptimizerFailRouteImport } from './routes/internal.optimizer.fail'
import { Route as InternalOptimizerCompleteRouteImport } from './routes/internal.optimizer.complete'
import { Route as InternalOptimizerClaimRouteImport } from './routes/internal.optimizer.claim'
import { Route as CdnV1SplatRouteImport } from './routes/cdn.v1.$'
import { Route as ApiSyncUploadUrlRouteImport } from './routes/api.sync.upload-url'
import { Route as ApiSyncSnapshotRouteImport } from './routes/api.sync.snapshot'
import { Route as ApiSyncRunsRouteImport } from './routes/api.sync.runs'
import { Route as ApiSyncCompleteObjectRouteImport } from './routes/api.sync.complete-object'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiMediaMediaIdThumbnailRouteImport } from './routes/api.media.$mediaId.thumbnail'
import { Route as ApiMediaMediaIdPreviewRouteImport } from './routes/api.media.$mediaId.preview'
import { Route as ApiMediaMediaIdOriginalRouteImport } from './routes/api.media.$mediaId.original'
import { Route as ApiSyncRunsSyncRunIdCompleteRouteImport } from './routes/api.sync.runs.$syncRunId.complete'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalOptimizerFailRoute = InternalOptimizerFailRouteImport.update({
  id: '/internal/optimizer/fail',
  path: '/internal/optimizer/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalOptimizerCompleteRoute =
  InternalOptimizerCompleteRouteImport.update({
    id: '/internal/optimizer/complete',
    path: '/internal/optimizer/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalOptimizerClaimRoute = InternalOptimizerClaimRouteImport.update({
  id: '/internal/optimizer/claim',
  path: '/internal/optimizer/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CdnV1SplatRoute = CdnV1SplatRouteImport.update({
  id: '/cdn/v1/$',
  path: '/cdn/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncUploadUrlRoute = ApiSyncUploadUrlRouteImport.update({
  id: '/api/sync/upload-url',
  path: '/api/sync/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncSnapshotRoute = ApiSyncSnapshotRouteImport.update({
  id: '/api/sync/snapshot',
  path: '/api/sync/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRunsRoute = ApiSyncRunsRouteImport.update({
  id: '/api/sync/runs',
  path: '/api/sync/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncCompleteObjectRoute = ApiSyncCompleteObjectRouteImport.update({
  id: '/api/sync/complete-object',
  path: '/api/sync/complete-object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdThumbnailRoute =
  ApiMediaMediaIdThumbnailRouteImport.update({
    id: '/api/media/$mediaId/thumbnail',
    path: '/api/media/$mediaId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaMediaIdPreviewRoute = ApiMediaMediaIdPreviewRouteImport.update({
  id: '/api/media/$mediaId/preview',
  path: '/api/media/$mediaId/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdOriginalRoute = ApiMediaMediaIdOriginalRouteImport.update({
  id: '/api/media/$mediaId/original',
  path: '/api/media/$mediaId/original',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRunsSyncRunIdCompleteRoute =
  ApiSyncRunsSyncRunIdCompleteRouteImport.update({
    id: '/$syncRunId/complete',
    path: '/$syncRunId/complete',
    getParentRoute: () => ApiSyncRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GalleryIndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/complete-object': typeof ApiSyncCompleteObjectRoute
  '/api/sync/runs': typeof ApiSyncRunsRouteWithChildren
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/sync/upload-url': typeof ApiSyncUploadUrlRoute
  '/cdn/v1/$': typeof CdnV1SplatRoute
  '/internal/optimizer/claim': typeof InternalOptimizerClaimRoute
  '/internal/optimizer/complete': typeof InternalOptimizerCompleteRoute
  '/internal/optimizer/fail': typeof InternalOptimizerFailRoute
  '/api/media/$mediaId/original': typeof ApiMediaMediaIdOriginalRoute
  '/api/media/$mediaId/preview': typeof ApiMediaMediaIdPreviewRoute
  '/api/media/$mediaId/thumbnail': typeof ApiMediaMediaIdThumbnailRoute
  '/api/sync/runs/$syncRunId/complete': typeof ApiSyncRunsSyncRunIdCompleteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof GalleryIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/complete-object': typeof ApiSyncCompleteObjectRoute
  '/api/sync/runs': typeof ApiSyncRunsRouteWithChildren
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/sync/upload-url': typeof ApiSyncUploadUrlRoute
  '/cdn/v1/$': typeof CdnV1SplatRoute
  '/internal/optimizer/claim': typeof InternalOptimizerClaimRoute
  '/internal/optimizer/complete': typeof InternalOptimizerCompleteRoute
  '/internal/optimizer/fail': typeof InternalOptimizerFailRoute
  '/api/media/$mediaId/original': typeof ApiMediaMediaIdOriginalRoute
  '/api/media/$mediaId/preview': typeof ApiMediaMediaIdPreviewRoute
  '/api/media/$mediaId/thumbnail': typeof ApiMediaMediaIdThumbnailRoute
  '/api/sync/runs/$syncRunId/complete': typeof ApiSyncRunsSyncRunIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/health': typeof ApiHealthRoute
  '/_gallery/': typeof GalleryIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/complete-object': typeof ApiSyncCompleteObjectRoute
  '/api/sync/runs': typeof ApiSyncRunsRouteWithChildren
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/sync/upload-url': typeof ApiSyncUploadUrlRoute
  '/cdn/v1/$': typeof CdnV1SplatRoute
  '/internal/optimizer/claim': typeof InternalOptimizerClaimRoute
  '/internal/optimizer/complete': typeof InternalOptimizerCompleteRoute
  '/internal/optimizer/fail': typeof InternalOptimizerFailRoute
  '/api/media/$mediaId/original': typeof ApiMediaMediaIdOriginalRoute
  '/api/media/$mediaId/preview': typeof ApiMediaMediaIdPreviewRoute
  '/api/media/$mediaId/thumbnail': typeof ApiMediaMediaIdThumbnailRoute
  '/api/sync/runs/$syncRunId/complete': typeof ApiSyncRunsSyncRunIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage'
    | '/api/health'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/complete-object'
    | '/api/sync/runs'
    | '/api/sync/snapshot'
    | '/api/sync/upload-url'
    | '/cdn/v1/$'
    | '/internal/optimizer/claim'
    | '/internal/optimizer/complete'
    | '/internal/optimizer/fail'
    | '/api/media/$mediaId/original'
    | '/api/media/$mediaId/preview'
    | '/api/media/$mediaId/thumbnail'
    | '/api/sync/runs/$syncRunId/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/manage'
    | '/api/health'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/complete-object'
    | '/api/sync/runs'
    | '/api/sync/snapshot'
    | '/api/sync/upload-url'
    | '/cdn/v1/$'
    | '/internal/optimizer/claim'
    | '/internal/optimizer/complete'
    | '/internal/optimizer/fail'
    | '/api/media/$mediaId/original'
    | '/api/media/$mediaId/preview'
    | '/api/media/$mediaId/thumbnail'
    | '/api/sync/runs/$syncRunId/complete'
  id:
    | '__root__'
    | '/_gallery'
    | '/login'
    | '/manage'
    | '/api/health'
    | '/_gallery/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/complete-object'
    | '/api/sync/runs'
    | '/api/sync/snapshot'
    | '/api/sync/upload-url'
    | '/cdn/v1/$'
    | '/internal/optimizer/claim'
    | '/internal/optimizer/complete'
    | '/internal/optimizer/fail'
    | '/api/media/$mediaId/original'
    | '/api/media/$mediaId/preview'
    | '/api/media/$mediaId/thumbnail'
    | '/api/sync/runs/$syncRunId/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GalleryRoute: typeof GalleryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManageRoute: typeof ManageRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiSyncCompleteObjectRoute: typeof ApiSyncCompleteObjectRoute
  ApiSyncRunsRoute: typeof ApiSyncRunsRouteWithChildren
  ApiSyncSnapshotRoute: typeof ApiSyncSnapshotRoute
  ApiSyncUploadUrlRoute: typeof ApiSyncUploadUrlRoute
  CdnV1SplatRoute: typeof CdnV1SplatRoute
  InternalOptimizerClaimRoute: typeof InternalOptimizerClaimRoute
  InternalOptimizerCompleteRoute: typeof InternalOptimizerCompleteRoute
  InternalOptimizerFailRoute: typeof InternalOptimizerFailRoute
  ApiMediaMediaIdOriginalRoute: typeof ApiMediaMediaIdOriginalRoute
  ApiMediaMediaIdPreviewRoute: typeof ApiMediaMediaIdPreviewRoute
  ApiMediaMediaIdThumbnailRoute: typeof ApiMediaMediaIdThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery': {
      id: '/_gallery'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery/': {
      id: '/_gallery/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/optimizer/fail': {
      id: '/internal/optimizer/fail'
      path: '/internal/optimizer/fail'
      fullPath: '/internal/optimizer/fail'
      preLoaderRoute: typeof InternalOptimizerFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/optimizer/complete': {
      id: '/internal/optimizer/complete'
      path: '/internal/optimizer/complete'
      fullPath: '/internal/optimizer/complete'
      preLoaderRoute: typeof InternalOptimizerCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/optimizer/claim': {
      id: '/internal/optimizer/claim'
      path: '/internal/optimizer/claim'
      fullPath: '/internal/optimizer/claim'
      preLoaderRoute: typeof InternalOptimizerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdn/v1/$': {
      id: '/cdn/v1/$'
      path: '/cdn/v1/$'
      fullPath: '/cdn/v1/$'
      preLoaderRoute: typeof CdnV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/upload-url': {
      id: '/api/sync/upload-url'
      path: '/api/sync/upload-url'
      fullPath: '/api/sync/upload-url'
      preLoaderRoute: typeof ApiSyncUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/snapshot': {
      id: '/api/sync/snapshot'
      path: '/api/sync/snapshot'
      fullPath: '/api/sync/snapshot'
      preLoaderRoute: typeof ApiSyncSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/runs': {
      id: '/api/sync/runs'
      path: '/api/sync/runs'
      fullPath: '/api/sync/runs'
      preLoaderRoute: typeof ApiSyncRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/complete-object': {
      id: '/api/sync/complete-object'
      path: '/api/sync/complete-object'
      fullPath: '/api/sync/complete-object'
      preLoaderRoute: typeof ApiSyncCompleteObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId/thumbnail': {
      id: '/api/media/$mediaId/thumbnail'
      path: '/api/media/$mediaId/thumbnail'
      fullPath: '/api/media/$mediaId/thumbnail'
      preLoaderRoute: typeof ApiMediaMediaIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId/preview': {
      id: '/api/media/$mediaId/preview'
      path: '/api/media/$mediaId/preview'
      fullPath: '/api/media/$mediaId/preview'
      preLoaderRoute: typeof ApiMediaMediaIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId/original': {
      id: '/api/media/$mediaId/original'
      path: '/api/media/$mediaId/original'
      fullPath: '/api/media/$mediaId/original'
      preLoaderRoute: typeof ApiMediaMediaIdOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/runs/$syncRunId/complete': {
      id: '/api/sync/runs/$syncRunId/complete'
      path: '/$syncRunId/complete'
      fullPath: '/api/sync/runs/$syncRunId/complete'
      preLoaderRoute: typeof ApiSyncRunsSyncRunIdCompleteRouteImport
      parentRoute: typeof ApiSyncRunsRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface ApiSyncRunsRouteChildren {
  ApiSyncRunsSyncRunIdCompleteRoute: typeof ApiSyncRunsSyncRunIdCompleteRoute
}

const ApiSyncRunsRouteChildren: ApiSyncRunsRouteChildren = {
  ApiSyncRunsSyncRunIdCompleteRoute: ApiSyncRunsSyncRunIdCompleteRoute,
}

const ApiSyncRunsRouteWithChildren = ApiSyncRunsRoute._addFileChildren(
  ApiSyncRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GalleryRoute: GalleryRouteWithChildren,
  LoginRoute: LoginRoute,
  ManageRoute: ManageRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiSyncCompleteObjectRoute: ApiSyncCompleteObjectRoute,
  ApiSyncRunsRoute: ApiSyncRunsRouteWithChildren,
  ApiSyncSnapshotRoute: ApiSyncSnapshotRoute,
  ApiSyncUploadUrlRoute: ApiSyncUploadUrlRoute,
  CdnV1SplatRoute: CdnV1SplatRoute,
  InternalOptimizerClaimRoute: InternalOptimizerClaimRoute,
  InternalOptimizerCompleteRoute: InternalOptimizerCompleteRoute,
  InternalOptimizerFailRoute: InternalOptimizerFailRoute,
  ApiMediaMediaIdOriginalRoute: ApiMediaMediaIdOriginalRoute,
  ApiMediaMediaIdPreviewRoute: ApiMediaMediaIdPreviewRoute,
  ApiMediaMediaIdThumbnailRoute: ApiMediaMediaIdThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
