name: Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.1.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod=false

      - name: Run Build
        run: pnpm run build:all
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""
      
      - name: Run Format
        run: pnpm format
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""

      - name: Run Lint Biome
        run: pnpm run lint:biome
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""

      - name: Run Lint Oxlint
        run: pnpm run lint:oxlint
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""

      - name: Run Typecheck
        run: pnpm run typecheck
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""

      - name: Run Knip
        run: pnpm run knip
        env:
          LOCKSTEP_API_URL: ""
          LOCKSTEP_API_TOKEN: ""